[workspace]

members = [
	"binary_tree",
	"builder_type", 
	"collatz",
	"counter",
	"elevator_event",
	"expression_evaluation",
	"fibonnaci",
	"geometry",
	"generic_min",
	"gui_lib",
	"health_stats",
	"iterator_chain",
	"luhn",
	"nested_arrays",
	"protobuf_parsing",
	"rewrite_with_result",
]
